# https://github.com/cachix/devenv/blob/bc8b21628907c726c74094cedc439c10a455cdb7/docs/src/integrations/github-actions.md?plain=1#L128-L160
name: "Test"

on:
  pull_request:
  push:

jobs:
  tests:
    strategy:
      matrix:
        os: [macos-15]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3 # v31
      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile add nixpkgs/8c50a710ddca43d7a530fb805ad55bde8d0141c5#devenv
      - name: Build the devenv shell and run any pre-commit hooks
        run: devenv test
      - name: Run a single command in the devenv shell
        run: devenv shell hello
      - run: devenv shell release
      # https://github.com/softprops/action-gh-release/blob/718ea10b132b3b2eba29c1007bb80653f286566b/README.md?plain=1#L110-L114
      - name: Release
        uses: softprops/action-gh-release@718ea10b132b3b2eba29c1007bb80653f286566b # v3.0.1
        if: github.ref_type == 'tag'
        with:
          files: plugin.tar.gz
# https://github.com/softprops/action-gh-release/blob/718ea10b132b3b2eba29c1007bb80653f286566b/README.md?plain=1#L289-L290
permissions:
  contents: write
